### ISSUE TITLE
ctypes_patch introspection fails on iOS apps packaged for distribution

### ISSUE THREAD

**Issue by freakboy3742** [beeware/rubicon-objc#104]
The ctypes_patch introduced in #85 works fine on macOS, iOS Simulator, and iOS devices in developer mode. However, when an iOS app is compiled and bundled for distribution (either App Store or Ad Hoc), the bitcode recompilation process appears to munge things in such a way that the ctypes patch fails.

### Reproduction instructions
* Create an iPhone app that uses Python 3.6 and Rubicon 0.2.10
* Export the app for Ad Hoc distribution
* Run the app. It will crash with the following stack trace:

```
 Traceback (most recent call last):
   File "/var/containers/Bundle/Application/CE92BB63-8128-4885-81ED-6955F3E15984/Travel Tips.app/Library/Application Support/com.keith-magee.traveltips/app/traveltips/__main__.py", line 10, in <module>
     main().main_loop()
   File "/var/containers/Bundle/Application/CE92BB63-8128-4885-81ED-6955F3E15984/Travel Tips.app/Library/Application Support/com.keith-magee.traveltips/app/traveltips/app.py", line 256, in main
     return TravelTips('Travel Tips', 'com.keith-magee.traveltips')
   File "/var/containers/Bundle/Application/CE92BB63-8128-4885-81ED-6955F3E15984/Travel Tips.app/Library/Application Support/com.keith-magee.traveltips/app_packages/toga/app.py", line 54, in __init__
     self.factory = get_platform_factory(factory)
   File "/var/containers/Bundle/Application/CE92BB63-8128-4885-81ED-6955F3E15984/Travel Tips.app/Library/Application Support/com.keith-magee.traveltips/app_packages/toga/platform.py", line 24, in get_platform_factory
     from toga_iOS import factory
   File "/var/containers/Bundle/Application/CE92BB63-8128-4885-81ED-6955F3E15984/Travel Tips.app/Library/Application Support/com.keith-magee.traveltips/app_packages/toga_iOS/factory.py", line 1, in <module>
     from .app import App, MainWindow
   File "/var/containers/Bundle/Application/CE92BB63-8128-4885-81ED-6955F3E15984/Travel Tips.app/Library/Application Support/com.keith-magee.traveltips/app_packages/toga_iOS/app.py", line 3, in <module>
     from rubicon.objc import objc_method
   File "/var/containers/Bundle/Application/CE92BB63-8128-4885-81ED-6955F3E15984/Travel Tips.app/Library/Application Support/com.keith-magee.traveltips/app_packages/rubicon/objc/__init__.py", line 3, in <module>
     from .runtime import (  # noqa: F401
   File "/var/containers/Bundle/Application/CE92BB63-8128-4885-81ED-6955F3E15984/Travel Tips.app/Library/Application Support/com.keith-magee.traveltips/app_packages/rubicon/objc/runtime.py", line 13, in <module>
     from . import ctypes_patch
   File "/var/containers/Bundle/Application/CE92BB63-8128-4885-81ED-6955F3E15984/Travel Tips.app/Library/Application Support/com.keith-magee.traveltips/app_packages/rubicon/objc/ctypes_patch.py", line 112, in <module>
     ctypes.pythonapi.PyType_stgdict.restype = ctypes.POINTER(StgDictObject)
   File "/var/containers/Bundle/Application/CE92BB63-8128-4885-81ED-6955F3E15984/Travel Tips.app/Library/Python/lib/python36.zip/ctypes/__init__.py", line 361, in __getattr__
   File "/var/containers/Bundle/Application/CE92BB63-8128-4885-81ED-6955F3E15984/Travel Tips.app/Library/Python/lib/python36.zip/ctypes/__init__.py", line 366, in __getitem__
   AttributeError: dlsym(RTLD_DEFAULT, PyType_stgdict): symbol not found
```

This error *does not* appear if you run the app on an attached debug device. It only occurs during Ad Hoc or App Store distribution. 

### Helpful hints

When distributing for Ad Hoc or App Store distribution, you only get the contents of NSLog. Output to Stdout and stderr (which is to say *all* Python output) isn't captured. Therefore, you'll need to capture stdout and stderr to a file, and dump that file on exit. 

The failure occurs when running the Python script, so if your app delegate is defined in Python, that delegate won't execute - and as a result, and pipe or GCD-based logging redirection won't activate.

**Comment by freakboy3742** [comment]
If you comment out the import of the ctypes_patch module (line 13 of runtime.py) the app works; so it's just a problem with introspecting the Python library.

**Comment by dgelessus** [comment]
Hm, I'm guessing that something in the build process for distribution is stripping the `PyType_stgdict` symbol out. Can you run `nm -a` on the distribution build's Python binary and upload the output as a Gist or something? I'd be interested in seeing whether the distribution binary has any useful symbols at all.

**Comment by freakboy3742** [comment]
Unfortunately not (or, at least, I'm not sure how I'd do it). The problem only manifests in an Ad Hoc or Distribution build, at which point you've only got an IPA, not a library you can usefully introspect. I'll poke around and see if I can find any way to pull apart an IPA to see what's inside...

**Comment by dgelessus** [comment]
IPAs are just ZIP archives as far as I know, so you can change the extension or drop them onto Archive Utility to extract them. Inside is a normal iOS .app bundle, you can "Show Package Contents" on it and the binaries should be inside.

**Comment by freakboy3742** [comment]
Oh - I didn't realise IPA files were just ZIP archives... Here's an NM dump for an nm dump of an Ad Hoc build (which crashes), and a development build in release mode (which doesn't). 

https://gist.github.com/freakboy3742/49fc0a92921bd0bc3f1bc3c940ca4aea

You're right - it looks like all the unused symbols are being stripped. I wonder if just instantiating an instance of PyType_stgdict in the mainline (not actually using it - just instantiating it in C so that the symbol *exists*) will do the job...

**Comment by dgelessus** [comment]
Actually I think *all* symbol exports are being stripped, except for `__mh_execute_header`, the main entry point. All the other symbols in the `nm` list are imports from system libraries. I'm guessing this is just an optimization - since this is the main application binary, nothing other than the binary itself ever needs its symbols, so they can be stripped (and all internal uses can be replaced with static addresses). Of course this is an issue when we want to look up symbols in the application binary at runtime...

One possible solution would be to not compile/statically link Python into the main binary, but instead make it a separate dynamic library or framework. This is how it's done in Pythonista - there is a `Py3Kit.framework` that contains the Python runtime, and looking up symbols in `ctypes.pythonapi` works fine in Pythonista.

**Comment by freakboy3742** [comment]
I seem to recall that dynamic libraries were a problem on older iOS versions, which is why the current BeeWare builds are all static linked. However, if that requirement has been relaxed, dynamic libs might be a better approach...

**Comment by cculianu** [comment]
You can get this working for distribution by modifying the project settings to disable stripping and/or bitcode.  Go to the build settings and set the following for the release builds:

         "Strip Debug Symbols During Copy" = NO 
         "Strip Linked Product" = NO 
         "Strip Style" = Debugging Symbols 
         "Enable Bitcode" = NO 

I also encountered this issue and the above fixed it.

The disabling of Bitcode isn't the end of the world -- your apps generally will run ok without it.  It's only for future-proofing with future versions of iOS and processor arch's.

**Comment by freakboy3742** [comment]
Following up on this - making the changes referred to by @cculianu didn't fix the problem for me, but after some more fiddling with xcode build settings, it appears that the `"Enable Testability"  =YES` setting *does*. This is set to "NO" for release by default.

I have no idea why this works, but I've found a couple of references that suggest that it might be related to having a static library compiled with `-fvisibility=hidden`.

**Comment by cculianu** [comment]
Good to know.. thanks for the update.  It's always a struggle getting this stuff to work right as Apple changes things..

**Comment by freakboy3742** [comment]
I'm going to close this; it looks as if the current Rubicon, combined with the "enable testability" change in Xcode (which has been added into the Briefcase iOS template) resolves this issue.
