### ISSUE TITLE
No method "terminate"

### ISSUE THREAD

**Issue by saroad2** [beeware/rubicon-objc#170]
Hey.

usually I run my beeware project [Eddington](https://github.com/EddLabs/eddington_gui) on Windows, where it works absolutly fine. I tryed to run the same project on Mac and got the following error:

```
Traceback (most recent call last):
  File "/Users/sshadur/PycharmProjects/eddington_gui/venv/lib/python3.7/site-packages/rubicon/objc/api.py", line 176, in __call__
    meth, order = self.methods[rest]
KeyError: frozenset()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/sshadur/PycharmProjects/eddington_gui/src/eddington_gui/__main__.py", line 4, in <module>
    main().main_loop()
  File "/Users/sshadur/PycharmProjects/eddington_gui/venv/lib/python3.7/site-packages/toga/app.py", line 427, in main_loop
    self._impl.main_loop()
  File "/Users/sshadur/PycharmProjects/eddington_gui/venv/lib/python3.7/site-packages/toga_cocoa/app.py", line 187, in main_loop
    self.loop.run_forever(lifecycle=CocoaLifecycle(self.native))
  File "/Users/sshadur/PycharmProjects/eddington_gui/venv/lib/python3.7/site-packages/rubicon/objc/eventloop.py", line 444, in run_forever
    self.stop()
  File "/Users/sshadur/PycharmProjects/eddington_gui/venv/lib/python3.7/site-packages/rubicon/objc/eventloop.py", line 524, in stop
    self._lifecycle.stop()
  File "/Users/sshadur/PycharmProjects/eddington_gui/venv/lib/python3.7/site-packages/rubicon/objc/eventloop.py", line 638, in stop
    self._application.terminate()
  File "/Users/sshadur/PycharmProjects/eddington_gui/venv/lib/python3.7/site-packages/rubicon/objc/api.py", line 206, in __call__
    return self.method(self.receiver, *args, **kwargs)
  File "/Users/sshadur/PycharmProjects/eddington_gui/venv/lib/python3.7/site-packages/rubicon/objc/api.py", line 180, in __call__
    .format(self.name_start, set(kwargs), "\n".join(repr(parts) for parts in self.methods))
ValueError: No method was found starting with 'terminate' and with selector parts set()
Known selector parts are:
frozenset({''})
```

I Don't know if it's a problem here or in *Toga*, but I would appreciate If you take a look at it.

**Comment by freakboy3742** [comment]
That's definitely an odd one... and I can't reproduce it either; in both dev and full build mode under Briefcase, I get what looks like a working GUI:

<img width="1212" alt="Screen Shot 2020-04-23 at 5 42 36 pm" src="https://user-images.githubusercontent.com/37345/80084757-df349380-8589-11ea-9058-c9cb43bd30b5.png">

That's under Mojave (10.14). What can you tell us about the machine you're using?

**Comment by saroad2** [comment]
The bug happens when I press the "plot data" button.

A way to reproduce the problem:

1. Download [sagi.txt](https://github.com/beeware/rubicon-objc/files/4521773/sagi.txt)
2. change the suffix from ".txt" to ".csv" (github doesn't allow to upload csv files to issues )
3. Open Eddington using "briefcase dev" and the GUI will open.
4. next to the  "input" line press the "choose file" button and choose the "sagi.csv" you just downloaded.
5. press the "plot data" button bellow and a matplotlib graph window would show up.
6. close the graph window using the "x" button
7. the bug reproduces.

I'm using MacBook Pro with version Catalina (10.15.3).

**Comment by dgelessus** [comment]
The error message here isn't very nice... The error is saying that the Rubicon event loop integration tried to call a method `terminate` (with no arguments) on the application object, but it could only find a method `terminate:` (with one argument). This makes sense - Apple's documentation for [`NSApplication`](https://developer.apple.com/documentation/appkit/nsapplication?language=objc) only lists the one-argument [`terminate:`](https://developer.apple.com/documentation/appkit/nsapplication/1428417-terminate?language=objc) method, and there is no mention of a zero-arg `terminate` method.

I don't know why nobody has run into this error before. Perhaps the event loop's `stop` method is not called during normal execution, or perhaps `NSApplication` used to have a private `terminate` with no arguments that we called by accident. (I haven't looked into this in detail yet.) But I'm fairly sure that this is a bug in Rubicon's event loop integration, so this is indeed the correct place for this issue. Thank you for the bug report!

**Comment by freakboy3742** [comment]
@saroad2 I've tried reproducing the error you describe, and I keep hitting other errors. Using hash 73cbf4366 of eddington_gui, I had to modify a call to PlotConfiguration.build() just to get the code to run, and install the dev version of Toga; with those changes, I was able to load the data file, but plotting didn't display anything.

#170 implements a speculative fix, but I can't validate if it works. If you can test it in your confiuguration, I'll gladly merge it in.

**Comment by saroad2** [comment]
It seems like this have fixed the original  problem, Thank you for that! On the other hand, after I repeat the steps I mentioned above it crashed, now without printing any error.

The reason it didn't reproduce for you is that I forget to mention that I'm working on branch *dev*, not *master*.

If you have the time and you would like to take a look at it again, It would really help me :).

**Comment by freakboy3742** [comment]
@saroad2 I've tried again with the dev branch; I now get a hard lockup when I click the PlotData button (and a really weird lockup, too - one where the *macOS* icon disappears after a force quit, but the app window remains open, beachballing, with a "Python (not responding)" entry in the activity monitor....)

**Comment by saroad2** [comment]
That's extremely wierd. For me it's just crashing without printing an error, nothing like that.

**Comment by saroad2** [comment]
Do you think that instead of using `plt.show()` we would print the plot to a `toga.Chart`  from [here](https://github.com/beeware/toga_chart) that would fix the problem?

**Comment by freakboy3742** [comment]
I wouldn't be surprised if having wxWindows and Toga in the same app is the cause of the problem; in which case, a native implementation of the charting might be a more viable option. 

I haven't looked at that chart code in a while, though, so it may not be ready-to-use in it's current form. I'd love to find out, though... :-)

**Comment by saroad2** [comment]
so, It's not longer relevant to *rubicon-objc*, but I put it here for the continuation of the discussions:
I removed the usage of *wxAgg* (put the lines calling it in *src/eddington_gui/__init__.py* in comments) and ran it again I got the following error this time:

```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rubicon/objc/api.py", line 232, in __call__
    result = self.py_method(py_self, *args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/toga_cocoa/app.py", line 72, in application_openFiles_
    self.impl.open_document(str(fileURL.absoluteString))
AttributeError: 'App' object has no attribute 'open_document'
```

It is more of a *Toga* error, but I thought to keep it in context. @freakboy3742 , have any idea what is it now?

**Comment by dgelessus** [comment]
The original issue has been fixed now (and as a result GitHub has automatically closed this issue). @saroad2 The error that you're getting now doesn't seem to be related to the original issue, and it seems to be related to Toga rather than Rubicon, so it would be better if you could open a new issue on the Toga repo instead. In the new issue you can include a link to this issue to keep the discussion context.

Thank you again for the bug report!
