### ISSUE TITLE
Superclass overrides of partials fail lookups

### ISSUE THREAD

**Issue by freakboy3742** [beeware/rubicon-objc#216]
The Toga HelloWorld project started failing on iOS 15, with the error
```
Exception ignored on calling ctypes callback function: <rubicon.objc.api.objc_method object at 0x12c5dbca0>
2021-11-12 14:48:28.039183+0800 Hello World[32406:17732749] Traceback (most recent call last):
2021-11-12 14:48:28.039309+0800 Hello World[32406:17732749]   File "/Users/rkm/Library/Developer/CoreSimulator/Devices/6ABA4842-DA4E-461D-9FB6-5E370B00012C/data/Containers/Bundle/Application/BE51B6F0-8547-4262-8417-B0DD9D57DA84/Hello World.app/Library/Application Support/com.example.helloworld/app_packages/rubicon/objc/api.py", line 271, in __call__
2021-11-12 14:48:28.039640+0800 Hello World[32406:17732749]     result = self.py_method(py_self, *args)
2021-11-12 14:48:28.039778+0800 Hello World[32406:17732749]   File "/Users/rkm/Library/Developer/CoreSimulator/Devices/6ABA4842-DA4E-461D-9FB6-5E370B00012C/data/Containers/Bundle/Application/BE51B6F0-8547-4262-8417-B0DD9D57DA84/Hello World.app/Library/Application Support/com.example.helloworld/app_packages/toga_iOS/app.py", line 46, in application_didFinishLaunchingWithOptions_
2021-11-12 14:48:28.040023+0800 Hello World[32406:17732749]     App.app.create()
2021-11-12 14:48:28.040137+0800 Hello World[32406:17732749]   File "/Users/rkm/Library/Developer/CoreSimulator/Devices/6ABA4842-DA4E-461D-9FB6-5E370B00012C/data/Containers/Bundle/Application/BE51B6F0-8547-4262-8417-B0DD9D57DA84/Hello World.app/Library/Application Support/com.example.helloworld/app_packages/toga_iOS/app.py", line 105, in create
2021-11-12 14:48:28.040375+0800 Hello World[32406:17732749]     self.interface.startup()
2021-11-12 14:48:28.040490+0800 Hello World[32406:17732749]   File "/Users/rkm/Library/Developer/CoreSimulator/Devices/6ABA4842-DA4E-461D-9FB6-5E370B00012C/data/Containers/Bundle/Application/BE51B6F0-8547-4262-8417-B0DD9D57DA84/Hello World.app/Library/Application Support/com.example.helloworld/app/helloworld/app.py", line 40, in startup
2021-11-12 14:48:28.040746+0800 Hello World[32406:17732749]     button = toga.Button(
2021-11-12 14:48:28.040896+0800 Hello World[32406:17732749]   File "/Users/rkm/Library/Developer/CoreSimulator/Devices/6ABA4842-DA4E-461D-9FB6-5E370B00012C/data/Containers/Bundle/Application/BE51B6F0-8547-4262-8417-B0DD9D57DA84/Hello World.app/Library/Application Support/com.example.helloworld/app_packages/toga/widgets/button.py", line 28, in __init__
2021-11-12 14:48:28.041126+0800 Hello World[32406:17732749]     self._impl = self.factory.Button(interface=self)
2021-11-12 14:48:28.041237+0800 Hello World[32406:17732749]   File "/Users/rkm/Library/Developer/CoreSimulator/Devices/6ABA4842-DA4E-461D-9FB6-5E370B00012C/data/Containers/Bundle/Application/BE51B6F0-8547-4262-8417-B0DD9D57DA84/Hello World.app/Library/Application Support/com.example.helloworld/app_packages/toga_iOS/widgets/base.py", line 13, in __init__
2021-11-12 14:48:28.041427+0800 Hello World[32406:17732749]     self.interface.style.reapply()
2021-11-12 14:48:28.041522+0800 Hello World[32406:17732749]   File "/Users/rkm/Library/Developer/CoreSimulator/Devices/6ABA4842-DA4E-461D-9FB6-5E370B00012C/data/Containers/Bundle/Application/BE51B6F0-8547-4262-8417-B0DD9D57DA84/Hello World.app/Library/Application Support/com.example.helloworld/app_packages/travertino/declaration.py", line 88, in reapply
2021-11-12 14:48:28.041713+0800 Hello World[32406:17732749]     self.apply(style, getattr(self, style))
2021-11-12 14:48:28.041822+0800 Hello World[32406:17732749]   File "/Users/rkm/Library/Developer/CoreSimulator/Devices/6ABA4842-DA4E-461D-9FB6-5E370B00012C/data/Containers/Bundle/Application/BE51B6F0-8547-4262-8417-B0DD9D57DA84/Hello World.app/Library/Application Support/com.example.helloworld/app_packages/toga/style/pack.py", line 104, in apply
2021-11-12 14:48:28.042065+0800 Hello World[32406:17732749]     self._applicator.set_font(
2021-11-12 14:48:28.042163+0800 Hello World[32406:17732749]   File "/Users/rkm/Library/Developer/CoreSimulator/Devices/6ABA4842-DA4E-461D-9FB6-5E370B00012C/data/Containers/Bundle/Application/BE51B6F0-8547-4262-8417-B0DD9D57DA84/Hello World.app/Library/Application Support/com.example.helloworld/app_packages/toga/style/applicator.py", line 25, in set_font
2021-11-12 14:48:28.042347+0800 Hello World[32406:17732749]     self.widget._impl.rehint()
2021-11-12 14:48:28.042443+0800 Hello World[32406:17732749]   File "/Users/rkm/Library/Developer/CoreSimulator/Devices/6ABA4842-DA4E-461D-9FB6-5E370B00012C/data/Containers/Bundle/Application/BE51B6F0-8547-4262-8417-B0DD9D57DA84/Hello World.app/Library/Application Support/com.example.helloworld/app_packages/toga_iOS/widgets/button.py", line 41, in rehint
2021-11-12 14:48:28.042648+0800 Hello World[32406:17732749]     fitting_size = self.native.systemLayoutSizeFittingSize(CGSize(0, 0))
2021-11-12 14:48:28.042743+0800 Hello World[32406:17732749]   File "/Users/rkm/Library/Developer/CoreSimulator/Devices/6ABA4842-DA4E-461D-9FB6-5E370B00012C/data/Containers/Bundle/Application/BE51B6F0-8547-4262-8417-B0DD9D57DA84/Hello World.app/Library/Application Support/com.example.helloworld/app_packages/rubicon/objc/api.py", line 232, in __call__
2021-11-12 14:48:28.042980+0800 Hello World[32406:17732749]     return self.method(self.receiver, *args, **kwargs)
2021-11-12 14:48:28.043070+0800 Hello World[32406:17732749]   File "/Users/rkm/Library/Developer/CoreSimulator/Devices/6ABA4842-DA4E-461D-9FB6-5E370B00012C/data/Containers/Bundle/Application/BE51B6F0-8547-4262-8417-B0DD9D57DA84/Hello World.app/Library/Application Support/com.example.helloworld/app_packages/rubicon/objc/api.py", line 204, in __call__
2021-11-12 14:48:28.043267+0800 Hello World[32406:17732749]     raise ValueError(
2021-11-12 14:48:28.043372+0800 Hello World[32406:17732749] ValueError: No method was found starting with 'systemLayoutSizeFittingSize' and with keywords set()
2021-11-12 14:48:28.043444+0800 Hello World[32406:17732749] Known keywords are:
2021-11-12 14:48:28.043540+0800 Hello World[32406:17732749] frozenset({'', 'withHorizontalFittingPriority', 'verticalFittingPriority'})
```

`systemLayoutSizeFittingSize:` has been available since iOS 6.0. A second version, `systemLayoutSize:withHorizontalFittingPriority:verticalFittingPriority:`, was added in iOS 8.0. These methods are defined on UIView. Neither method has been deprecated.

However, at an implementation level, iOS 15 appears to have added an override of `systemLayoutSize:withHorizontalFittingPriority:verticalFittingPriority:` on a UIButton (possibly other classes as well). As a result, when looking for `systemLayoutSizeFittingSize:`, the partial matches on UIButton; but UIButton doesn't explicitly define that variant, and so the lookup process fails.

**To Reproduce**

Run the HelloWorld tutorial for Toga on iOS, using iOS 15.

**Expected behavior**

A lookup for `systemLayoutSizeFittingSize:` on UIButton should succeed.

**Environment:**
 - Operating System: iOS 15.0 (it appears to work on iOS 14.5 and lower)
 - Python version: Any

**Additional Info**

As a workaround, you can invoke `button.systemLayoutSizeFittingSize_(...)` to access the method explicitly, rather than invoking `button.systemLayoutSizeFittingSize(...)` and relying on the partial lookup.

**Comment by freakboy3742** [comment]
Further exploration - it requires a 3 class inheritance chain. The problem exists because UIButton extends UIControl extends UIView; UIView defines the original implementations, but the override of a single method is on UIButton. By the look of it, `load_methods` is loading the partial definition of the *parent* class, but not all superclasses.
