### ISSUE TITLE
Blocks not fully working on M1 hardware

### ISSUE THREAD

**Issue by freakboy3742** [beeware/rubicon-objc#225]
**Describe the bug**
The Rubicon ObjC Test suite has failures when executed on M1 hardware. The failures are all in the tests of Block functionality; some, but not all tests are currently failing.

The test failures all appear to be related to the return values from block methods.

**To Reproduce**
1. Run the test suite on M1 hardware2. 
2. Test failures occur:
```
==============================================================================
FAIL: tests/test_blocks.py::BlockTests::test_block_bound_method
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rkm/beeware/rubicon/objc/tests/test_blocks.py", line 158, in test_block_bound_method
    self.assertEqual(returned_two_args_block(12, 34), 46)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: None != 46

==============================================================================
FAIL: tests/test_blocks.py::BlockTests::test_block_delegate_auto
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rkm/beeware/rubicon/objc/tests/test_blocks.py", line 53, in test_block_delegate_auto
    self.assertEqual(result, 9)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 9

==============================================================================
FAIL: tests/test_blocks.py::BlockTests::test_block_delegate_auto_struct
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rkm/beeware/rubicon/objc/tests/test_blocks.py", line 70, in test_block_delegate_auto_struct
    self.assertEqual(result, 85)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 85

==============================================================================
FAIL: tests/test_blocks.py::BlockTests::test_block_delegate_method_manual_ctypes
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rkm/beeware/rubicon/objc/tests/test_blocks.py", line 31, in test_block_delegate_method_manual_ctypes
    self.assertEqual(result, 5)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 5

==============================================================================
FAIL: tests/test_blocks.py::BlockTests::test_block_delegate_method_manual_pytypes
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rkm/beeware/rubicon/objc/tests/test_blocks.py", line 42, in test_block_delegate_method_manual_pytypes
    self.assertEqual(result, 5)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 5

==============================================================================
FAIL: tests/test_blocks.py::BlockTests::test_block_property_ctypes
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rkm/beeware/rubicon/objc/tests/test_blocks.py", line 14, in test_block_property_ctypes
    self.assertEqual(result, 3)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: None != 3

==============================================================================
FAIL: tests/test_blocks.py::BlockTests::test_block_property_pytypes
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rkm/beeware/rubicon/objc/tests/test_blocks.py", line 20, in test_block_property_pytypes
    self.assertEqual(result, 3)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: None != 3

==============================================================================
FAIL: tests/test_blocks.py::BlockTests::test_block_round_trip
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rkm/beeware/rubicon/objc/tests/test_blocks.py", line 118, in test_block_round_trip
    self.assertEqual(returned_block(8, 9), 17)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: None != 17

------------------------------------------------------------------------------
Ran 266 tests in 2.15s

FAILED (failures=8)
```

**Expected behavior**
Test suite should pass on M1 hardware

**Screenshots**

**Environment:**
 - M1 Mac hardware
 - Operating System: macOS 12.3.1
 - Python version: 3.8, 3.9, 3.10, 3.11

**Additional context**

It is likely that these failures are also occurring on iOS devices. CI testing this is going to be difficult...

**Comment by dgelessus** [comment]
Haven't had a detailed look yet, but I noticed that our `Block` class always sets the `HAS_STRET` flag on the block literal struct:

https://github.com/beeware/rubicon-objc/blob/d4533001eee0c7349ebf0007993e9489ba948fc6/rubicon/objc/api.py#L1946-L1948

This seems wrong - surely `HAS_STRET` should be set conditionally based on [`should_use_stret`](https://github.com/beeware/rubicon-objc/blob/d4533001eee0c7349ebf0007993e9489ba948fc6/rubicon/objc/runtime.py#L603) for the return type? (How did this not break on Intel already?)

**Comment by freakboy3742** [comment]
Not sure - seems possible that it's related. FWIW, the super-naïve approach of "only add `HAS_STRET` to `flags` if `should_use_stret(rettype) == True` isn't enough to fix the problem.

**Comment by freakboy3742** [comment]
I've done a little more investigation here; it appears that we *can* invoke a method that accepts a Block as an argument (so, the common case of "invoke method providing callback") works. It's the "round trip" cases that fail - if you want to retrieve a block as a property, and then use that block as a method.

**Comment by freakboy3742** [comment]
Following some investigation with @jeamland at PyCon AU - the problem appears to be that when the `invoke` property of the `ObjCBlockStruct` [is modifed](https://github.com/beeware/rubicon-objc/blob/main/src/rubicon/objc/api.py#L2164), the change to the `restype` isn't sticking - no matter what it is set to, it resets to `c_void_p`.

We were able to get a working return type by defining a custom ObjCBlockStruct with the desired invocation prototype on the fly, rather than tweaking a `_cfunc_type_block_invoke` definition; however, that wasn't enough to fix all the problems. This is likely because there are a number of different block types depending on whether the block has a signature, has a class, etc.

**Comment by freakboy3742** [comment]
After a day of investigation, I've been able to get each individual block test to pass - but not with a single codebase.

It appears that Blocks passing on x86 hardware is *almost* accidental - they have the same restype-not-sticking problem, but evidently this doesn't matter at runtime. I'm guessing that because all the examples are passing around integers, byte alignment isn't becoming a factor; and x86 is loose enough with type checks that the code is working. M1, however, is raising exceptions when the types of provided arguments don't match the actual function signature; those exceptions are being swallowed because of where they happen in the round-trip process, resulting in 0 return values for the test methods.

The fix is to set the `restype` and `argtypes` of the `invoke` method in the ObjCBlockStruct. However, there appears to be some inconsistency on whether the block itself is provided as an argument, or whether it's provided in the arguments at time of invocation, or implied as part of the binding of the block. If you manually control whether and how the block is passed in as an argument, you can get the block tests to pass on M1 - I just need to work out exactly what condition (and how to detect those conditions) to enable those new behaviours.
